version: "3.8"

services:
  app:
    build: .
    container_name: node_app
    working_dir: /home/node/app
    environment:
      DATABASE_URL: "postgresql://mern_test_backend_db_user:V4QfIqLo5d5wanm06ApksmxPYTbF4uxo@dpg-ctocnkpopnds73fh36lg-a.ohio-postgres.render.com/mern_test_backend_db"
    ports:
      - "3000:3000"